### PR TITLE
Fix #15, `script` crashing application

### LINKED ISSUE #15: Some thought about crashes when calling js from Nim
Similar to #5 , I went into some crashes when working with `hello_world.nim` using Nimble package.
In devel mode it crashes silently when clicked, in release mode it works but sometimes it still crashes.
I tried to change `webui.nim:261` from
```
data = buffer.join().strip(leading = false, chars = {'\x00'})
```
to
```
data = $(cast[cstring](addr buffer[0]))
```
Then it seems to work smoothly, with `thread:off`. Not tested much and not using nightly build, but I want to note it here for others who is willing to make further investigations about it.

My env: Nim Compiler Version 1.6.12 [Windows: amd64]

### PR DESCRIPTION
**Pull request by neroist**

### CODE REVIEW

File: webui.nim [hunk 1]
```diff
@@ -258,7 +256,7 @@ proc script*(window: Window; script: string; timeout: int = 0, bufferLen: static
   let 
     error = bindings.script(csize_t window, cstring script, csize_t timeout, cast[cstring](addr buffer), csize_t bufferLen)
```
Comment (clzls) [inline webui.nim:257]: I think it would be better to use `addr buffer[0]` for unified coding style here?

(Either may not be a safe option, through)

Comment (AlbertShown) [reply webui.nim:257]: @neroist is the best person to confirm that.
